clc;
close all;
clear all;

rootDir         = getRootProjectDirectory();
projectFolders  = getProjectFolders(rootDir);

addpath(projectFolders.aurora600A);
addpath(projectFolders.common);
addpath(projectFolders.postprocessing);
addpath(projectFolders.experiments);
addpath(fullfile(rootDir,'aurora600A_impedance'));

flag_0Presentation_1Publication = 1;

flag_makeCalibrationPlots         =0;
flag_makeFrequencyResponsePlots   =0;
flag_makeForceLengthImpedancePlots=0;
flag_makeImpedanceModelPlots      =1;

flag_savePlot=1;

if(flag_makeCalibrationPlots==1)
  calibrationExperiment = {'20260116_impedance_larb_spring'};
  calibrationTrials = {...
    'analysis_Passive_06_spring_020mN_100Lo_20260116_air.json',...
    'analysis_Passive_06_spring_020mN_100Lo_20260116_h2o.json'};
    
  for i=1:1:length(calibrationTrials)
    figCal = figure;
    figCal = plotCalibrationData600A(figCal,...
                                     calibrationExperiment, ...
                                     calibrationTrials{i},...
                                     projectFolders,...
                                     flag_0Presentation_1Publication,...
                                     flag_savePlot);
    close(figCal);
  end
end

if(flag_makeFrequencyResponsePlots==1)
  colorSeries=getPaulTolColourSchemes('vibrant');

  impedanceExperiment={'20251118_impedance_larb_1'};
  impedanceTrials ={'analysis_larb_07_passive_100Lo_20251118.json',...
                   'analysis_larb_08_active_100Lo_20251118.json'};
  activeState = [0,1];
  segmentId=2;

  figImp = figure;
  trialIdx=1;  
  legendEntries = {'Passive','Active'};
  trialColors=[colorSeries.blue;colorSeries.red];
  flag_storageLoss0_stiffnessDamping1_titles=0;
  figImp = plotFrequencyResponse600A(...
                        figImp,...
                        impedanceExperiment, ...
                        impedanceTrials, ...
                        segmentId,...
                        activeState,...
                        legendEntries,...                        
                        trialColors,...                        
                        projectFolders,...
                        flag_storageLoss0_stiffnessDamping1_titles,...
                        flag_0Presentation_1Publication,...
                        flag_savePlot);  
  close(figImp);
  figImp=figure;
  flag_storageLoss0_stiffnessDamping1_titles=1;
  figImp = plotFrequencyResponse600A(...
                        figImp,...
                        impedanceExperiment, ...
                        impedanceTrials, ...
                        segmentId,...
                        activeState,...
                        legendEntries,...                        
                        trialColors,...                        
                        projectFolders,...
                        flag_storageLoss0_stiffnessDamping1_titles,...
                        flag_0Presentation_1Publication,...
                        flag_savePlot);  
  close(figImp);  
end

if(flag_makeForceLengthImpedancePlots==1)
  experimentList = {  '20251118_impedance_larb_1',...
                      '20251118_impedance_larb_2',...
                      '20251120_impedance_larb_3',...
                      '20251121_impedance_larb_4',...
                      '20251121_impedance_larb_5',...
                      '20251128_impedance_larb_6',...
                      '20251203_impedance_larb_7'};
%   experimentList = {  '20251118_impedance_larb_1',...
%                       '20251118_impedance_larb_2'};

  categories.length.value = ...
    [0.55,0.70,0.85,1.00,1.15,1.30,1.45];
  categories.length.str   = ...
    {'055Lo','070Lo','085Lo','100Lo','115Lo','130Lo','145Lo'};  
  categories.length.indexLopt=4;
  categories.active.str   ={'active','passive'};

  figZL=figure;
  segmentId = 2;
  modeNormalization=0;

  ptColorSeries=getPaulTolColourSchemes('vibrant');

  figZL = plotForceLengthImpedance600A(...
                        figZL,...
                        experimentList, ...
                        segmentId,...
                        categories, ...
                        modeNormalization,...
                        projectFolders,...
                        '_smax',...
                        flag_0Presentation_1Publication,...
                        flag_savePlot);
  close(figZL);

  figZL=figure;
  segmentId = 2;
  modeNormalization=1;

  ptColorSeries=getPaulTolColourSchemes('vibrant');

  figZL = plotForceLengthImpedance600A(...
                        figZL,...
                        experimentList, ...
                        segmentId,...
                        categories, ...
                        modeNormalization,...
                        projectFolders,...
                        '_smax_lmax',...
                        flag_0Presentation_1Publication,...
                        flag_savePlot);
  close(figZL);
  
end

if(flag_makeImpedanceModelPlots==1)
  experimentList = {  '20251118_impedance_larb_1',...
                      '20251118_impedance_larb_2',...
                      '20251120_impedance_larb_3',...
                      '20251121_impedance_larb_4',...
                      '20251121_impedance_larb_5',...
                      '20251128_impedance_larb_6',...
                      '20251203_impedance_larb_7'};
                      
%                      '20251121_impedance_larb_5',...
  
%  experimentList = {  '20251118_impedance_larb_1',...
%                      '20251118_impedance_larb_2'};

  categories.length.value = ...
    [0.55,0.70,0.85,1.00,1.15,1.30,1.45];
  categories.length.str   = ...
    {'055Lo','070Lo','085Lo','100Lo','115Lo','130Lo','145Lo'};  
  categories.length.indexLopt=4;
  categories.active.str   ={'active','passive'};

  figZLM=figure;
  segmentId = 2;
  modeNormalization=0;

  figZLM = plotForceLengthImpedanceModel600A(...
                        figZLM,...
                        experimentList, ...
                        segmentId,...
                        categories, ...
                        modeNormalization,...
                        projectFolders,...
                        '_smax',...
                        flag_0Presentation_1Publication,...
                        flag_savePlot);
  close(figZLM);



end