function dataConfig = getImpedanceExperimentConfiguration600A(...
                            folderName,projectFolders)

dataConfig.folder = folderName;


switch dataConfig.folder
    case '20251031'
        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords = ...
            {'Passive_05_nitrile_020mN_100Lo_20251030_air.dat',...
             'Passive_05_nitrile_020mN_100Lo_20251030_h2o.dat',...
             'Passive_06_nitrile_020mN_100Lo_20251030_air.dat',...
             'Passive_06_nitrile_020mN_100Lo_20251030_h2o.dat',...
             'Passive_07_nitrile_020mN_100Lo_20251030_air.dat',...
             'Passive_07_nitrile_020mN_100Lo_20251030_h2o.dat',...
             'Passive_08_nitrile_020mN_100Lo_20251030_air.dat',...
             'Passive_08_nitrile_020mN_100Lo_20251030_h2o.dat'};

        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =zeros(nTrials,1);

        dataConfig.titleTrial = {'Nitrile (Air: Wave 1)',...
                                 'Nitrile (H2O: Wave 1)',...
                                 'Nitrile (Air: Wave 2)',...
                                 'Nitrile (H2O: Wave 2)',...
                                 'Nitrile (Air: Wave 3)',...
                                 'Nitrile (H2O: Wave 3)',...
                                 'Nitrile (Air: Wave 4)',...
                                 'Nitrile (H2O: Wave 4)'};   

        dataConfig.titleBlock = {'','','',''...
                                 '','','',''};

        dataConfig.lengthLimitsOffset = [-ones(nTrials,1),ones(nTrials,1)].*0.025;
        dataConfig.forceLimitsOffset  = [-ones(nTrials,1),ones(nTrials,1)].*3;        
        dataConfig.timeIntervalOffset =  ones(nTrials,2).*([0.750,0.950].*1000);
        
        lossPerTrial     = 0.0;
        idxTrialFmax     = 1;
        normalizeData    = 0;

        dataConfig.fmaxScaling = ones(nTrials,1);
        
        dataConfig.trialPlotColumn     = [1:8];
        dataConfig.trialUsedForFmax    = 1;
        dataConfig.bandwidthHz         = [ones(nTrials,1),ones(nTrials,1)].*[1.5,90];
        dataConfig.bandwidthHzPlot     = ...
            [zeros(nTrials,1), ...
             (ones(nTrials,1).*dataConfig.bandwidthHz(:,2)+1)];
        
        dataConfig.perturbationType = {'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic',...
                                       'Larb-Stochastic'};


        dataConfig.coherenceSqYLim      = [0,1].*ones(nTrials,2);
        dataConfig.gainNormYLim         = [0,110].*ones(nTrials,2);
        dataConfig.phaseYLim            = [-45,45].*ones(nTrials,2);
        dataConfig.addStressStrainPlot  = 1;        
        dataConfig.normalizeData = 0;        
    case '20251030'
        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords = ...
            {'02_nitrile_020mN_100Lo_20251029_active',...
             '02_nitrile_020mN_100Lo_20251029_passive'};

        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =[0;1];

        dataConfig.titleTrial = {'Rat EDL Active ($$1 \ell_o$$)',...
                                 'Rat EDL Passive ($$1 \ell_o$$)'};   

        dataConfig.titleBlock = {'',''};

        dataConfig.lengthLimitsOffset = [-ones(nTrials,1),ones(nTrials,1)].*0.025;
        dataConfig.forceLimitsOffset  = [-3,3;...
                                         -(2e-3),(2e-3)];
        dataConfig.timeIntervalOffset =  ones(nTrials,2).*([0.750,0.950].*1000);
        
        lossPerTrial     = 0.0;
        idxTrialFmax     = 1;
        normalizeData    = 1;

        dataConfig.fmaxScaling = [1;1];
        
        dataConfig.trialPlotColumn     = [1,2];
        dataConfig.trialUsedForFmax    = 1;
        dataConfig.bandwidthHz         = [ones(nTrials,1),ones(nTrials,1)].*[1.5,90];
        dataConfig.bandwidthHzPlot     = ...
            [zeros(nTrials,1), ...
             (ones(nTrials,1).*dataConfig.bandwidthHz(:,2)+1)];
        
        dataConfig.perturbationType = {'Larb-Stochastic',...
                                       'Larb-Stochastic'};


        dataConfig.coherenceSqYLim      = [0,1].*ones(nTrials,2);
        dataConfig.gainNormYLim         = [0,110].*ones(nTrials,2);
        dataConfig.phaseYLim            = [-45,45].*ones(nTrials,2);
        dataConfig.addStressStrainPlot  = 1;
        
        dataConfig.normalizeData = 0;

    case '20250904'
        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords = ...
            {'03_isometric_072Lo_20250904',...
             '04_isometric_107Lo_20250904'};

        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =ones(nTrials,1);

        dataConfig.titleTrial = {'($$0.72 \ell_o$$)',...
                                                     '($$1.07 \ell_o$$)'};   

        dataConfig.titleBlock = {'Passive','Active'};



        dataConfig.lengthLimitsOffset = [-ones(nTrials,1),ones(nTrials,1)].*0.003;
        dataConfig.forceLimitsOffset  = [-ones(nTrials,1),ones(nTrials,1)].*0.3;
        dataConfig.timeIntervalOffset =  ones(nTrials,2).*([0.750,0.950].*1000);
        
        lossPerTrial          = 0.02;
        idxTrialFmax        = 2;
        normalizeData    = 1;

        dataConfig.fmaxScaling = [(1-lossPerTrial)^-1,...
                                                            (1-lossPerTrial)^0];
        
        dataConfig.trialPlotColumn     = [1,2];
        dataConfig.trialUsedForFmax    = 2;
        dataConfig.bandwidthHz         = [ones(nTrials,1),ones(nTrials,1)].*[1.5,15];
        dataConfig.bandwidthHzPlot     = ...
            [zeros(nTrials,1), ...
             (ones(nTrials,1).*dataConfig.bandwidthHz(:,2)+1)];
        
        dataConfig.perturbationType = {'sine-high-frequency',...
                                                                        'sine-high-frequency'};


        dataConfig.coherenceSqYLim      = [0,1].*ones(nTrials,2);
        dataConfig.gainNormYLim            = [0,110].*ones(nTrials,2);
        dataConfig.phaseYLim                   = [-45,45].*ones(nTrials,2);
        dataConfig.addStressStrainPlot  = 1;
        
        dataConfig.normalizeData = 1;


    case '20250821'
        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords = ...
            {'04_isometric_06Lo_2025',...
             '05_isometric_10Lo_2025',...
             '06_isometric_14Lo_2025'};

        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.isActive =ones(nTrials,1);

        dataConfig.titleTrial = {'($$0.6 \ell_o$$)',...
                                '($$1.0 \ell_o$$)',...
                                '($$1.4 \ell_o$$)'};   

        dataConfig.titleBlock = {'Passive','Active'};

        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.lengthLimitsOffset = [-ones(nTrials,1),ones(nTrials,1)].*0.0025;
        dataConfig.forceLimitsOffset  = [-ones(nTrials,1),ones(nTrials,1)].*0.075;
        dataConfig.timeIntervalOffset = ones(nTrials,2).*([0.750,0.950].*1000);
        
        lossPerTrial     = 0.02;
        idxTrialFmax     = 2;
        normalizeData    = 1;

        dataConfig.fmaxScaling = [(1-lossPerTrial)^-1,...
                            (1-lossPerTrial)^0,...
                            (1-lossPerTrial)^1];
        
        dataConfig.trialPlotColumn     = [1,2,3];
        dataConfig.trialUsedForFmax    = 2;
        dataConfig.bandwidthHz         = [ones(nTrials,1),ones(nTrials,1)].*[1.5,10];
        dataConfig.bandwidthHzPlot     = ...
            [zeros(nTrials,1), ...
             (ones(nTrials,1).*dataConfig.bandwidthHz(:,2)+1)];
        
        dataConfig.perturbationType = {'sine-low-frequency',...
                            'sine-low-frequency',...
                            'sine-low-frequency'};


        dataConfig.coherenceSqYLim      = [0,1].*ones(nTrials,2);
        dataConfig.gainNormYLim         = [0,43].*ones(nTrials,2);
        dataConfig.phaseYLim            = [-20,20].*ones(nTrials,2);
        dataConfig.addStressStrainPlot  = 1;
        
        dataConfig.normalizeData = 1;

    case '20250823_fli_nitrile'
        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords =...
            {'00_nitrile_isometric_10Lo_20250823_empty',...
             '00_nitrile_isometric_10Lo_20250823_h2o',...
             '01_nitrile_isometric_10Lo_20250823_empty',...
             '01_nitrile_isometric_10Lo_20250823_h2o'};

        dataConfig.titleTrial = {  'air (0-20Hz)',...
                                'H20 (0-20Hz)',...
                                'air (0-10Hz)',...
                                'H20 (0-10Hz)'};   

        dataConfig.titleBlock = {'Nitrile (1/2)','Nitrile (2/2)'};

        
        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =zeros(nTrials,1);

        dataConfig.lengthLimitsOffset          = [];
        dataConfig.forceLimitsOffset           = [];
        dataConfig.timeIntervalOffset = ones(nTrials,2).*([0.750,0.950].*1000);
        
        dataConfig.fmaxScaling = ones(1,nTrials);
        idxTrialFmax     = [];
        normalizeData    = 0;
        

        dataConfig.trialPlotColumn  = [1,2,3,4];
        dataConfig.trialUsedForFmax = 1;
        dataConfig.bandwidthHz      = [1.5,20; 1.5,20; 1.5,10; 1.5,10];
        dataConfig.bandwidthHzPlot  = [zeros(nTrials,1),...
                                       (dataConfig.bandwidthHz(:,2)+1)];
        dataConfig.perturbationType = ...
            {'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-low-frequency',...
             'sine-low-frequency'};        
        


        
        dataConfig.coherenceSqYLim      = [];
        dataConfig.gainNormYLim         = [];
        dataConfig.phaseYLim            = [-75,5];
        dataConfig.addStressStrainPlot  = 1;


        dataConfig.addStressStrainPlot = 0;
        
        dataConfig.normalizeData = 1;

    case '20250823_fli_B1'

        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords ={...
            '01_isometric_06Lo_20250823',...
            '02_isometric_07Lo_20250823',...
            '03_isometric_08Lo_20250823',...
            '04_isometric_09Lo_20250823',...
            '05_isometric_10Lo_20250823',...
            '06_isometric_11Lo_20250823',...
            '07_isometric_12Lo_20250823',...
            '08_isometric_13Lo_20250823',...
            '09_isometric_14Lo_20250823'};


        dataConfig.titleTrial = {...
            '$$0.6 \ell_o$$',...
            '$$0.7 \ell_o$$',...
            '$$0.8 \ell_o$$',...
            '$$0.9 \ell_o$$',...
            '$$1.0 \ell_o$$',...
            '$$1.1 \ell_o$$',...
            '$$1.2 \ell_o$$',...
            '$$1.3 \ell_o$$',...
            '$$1.4 \ell_o$$'};   

        dataConfig.titleBlock = {'Passive','Active'};

        
        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =zeros(nTrials,1);

        dataConfig.lengthLimitsOffset          = [];
        dataConfig.forceLimitsOffset           = [];
        dataConfig.timeIntervalOffset = ones(nTrials,2).*([0.750,0.950].*1000);
        
        loss = 0.98;

        dataConfig.fmaxScaling = [...
            loss^(4),...
            loss^(3),...
            loss^(2),...
            loss^(1),...
            loss^0,...
            loss^-1,...
            loss^-2,...
            loss^-3,...
            loss^-4];


        

        dataConfig.trialPlotColumn  = [1:nTrials];
        dataConfig.trialUsedForFmax = 5;
        dataConfig.bandwidthHz      = ones(nTrials,2).*[1,20];
        dataConfig.bandwidthHzPlot  = [zeros(nTrials,1),...
                                       (dataConfig.bandwidthHz(:,2)+1)];
        dataConfig.perturbationType = ...
            {'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency'...          
             };        
        
        
        dataConfig.coherenceSqYLim      = [];
        dataConfig.gainNormYLim         = [];
        dataConfig.phaseYLim            = ones(nTrials,2).*[-75,5];
        dataConfig.addStressStrainPlot  = 1;
        
        dataConfig.normalizeData = 1;       
    case '20250823_fli_B2'

        dataConfig.path = fullfile(projectFolders.data_600A,dataConfig.folder);

        dataConfig.fileNameKeywords ={...
            '01_isometric_06Lo_20250823_2',...
            '02_isometric_07Lo_20250823',...
            '03_isometric_08Lo_20250823_2',...
            '04_isometric_09Lo_20250823',...
            '05_isometric_10Lo_20250823',...
            '06_isometric_11Lo_20250823',...
            '07_isometric_12Lo_20250823',...
            '08_isometric_13Lo_20250823',...
            '09_isometric_14Lo_20250823'};


        dataConfig.titleTrial = {...
            '$$0.6 \ell_o$$',...
            '$$0.7 \ell_o$$',...
            '$$0.8 \ell_o$$',...
            '$$0.9 \ell_o$$',...
            '$$1.0 \ell_o$$',...
            '$$1.1 \ell_o$$',...
            '$$1.2 \ell_o$$',...
            '$$1.3 \ell_o$$',...
            '$$1.4 \ell_o$$'};   

        dataConfig.titleBlock = {'Passive','Active'};

        
        nTrials = length(dataConfig.fileNameKeywords);
        dataConfig.numberOfTrials = nTrials;

        dataConfig.isActive =zeros(nTrials,1);

        dataConfig.lengthLimitsOffset          = [];
        dataConfig.forceLimitsOffset           = [];
        dataConfig.timeIntervalOffset = ones(nTrials,2).*([0.750,0.950].*1000);
        
        loss = 0.98;

        dataConfig.fmaxScaling = [...
            loss^(4),...
            loss^(3),...
            loss^(2),...
            loss^(1),...
            loss^0,...
            loss^-1,...
            loss^-2,...
            loss^-3,...
            loss^-4];


        

        dataConfig.trialPlotColumn  = [1:nTrials];
        dataConfig.trialUsedForFmax = 5;
        dataConfig.bandwidthHz      = ones(nTrials,2).*[1,20];
        dataConfig.bandwidthHzPlot  = [zeros(nTrials,1),...
                                       (dataConfig.bandwidthHz(:,2)+1)];
        dataConfig.perturbationType = ...
            {'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency',...
             'sine-high-frequency'...          
             };        
        
        
        dataConfig.coherenceSqYLim      = [];
        dataConfig.gainNormYLim         = [];
        dataConfig.phaseYLim            = ones(nTrials,2).*[-75,5];
        dataConfig.addStressStrainPlot  = 1;
        
        dataConfig.normalizeData = 1;               
    otherwise 
        assert(0,'Error: invalid dataConfig.folder');
end
