function errorVec = calcWaveError610A(argsVec, ...
                                          timeSample,...
                                          dataSample, ...
                                          params)


waveSample = createWave610A(argsVec,timeSample,params);

errorVec = waveSample ...
          -dataSample;

