function metaDataCache = getEmptyMetaDataCache610A()

metaDataCache = struct('indexMeasurement',0,...
                        'indexSequence',0,...
                        'indexTrial',0,...
                        'sequenceFileName','',...
                        'sequenceFilePath','',...
                        'sequenceJson',[],...
                        'metaDataJson',[],...
                        'metaDataFileName','',...
                        'metaDataFilePath','',...
                        'dataFileName','',...
                        'dataFilePath','',...
                        'dataSha256Sum','',...
                        'protocolFileName','',...
                        'protocolFilePath','',...
                        'tags',[],...
                        'temperature_C',0,...
                        'referenceState',[],...
                        'dimensions',[],...
                        'specimen',[],...
                        'isLastMeasurement',0);